### ISSUE TITLE
Add "Secret Test" in 980904

### ISSUE THREAD

**Issue by zero800** [jedpossum/alpha3#1]
Hello JED,
Very interesting your project, I tried a lot to remake the same thing using the IDA but I don't have your talent.
Would it be possible to copy the "Secret Test" from sfa3us and put it in your Assembler version?
Debug is very useful to create new moves and hitboxes.
Even if it's not possible to put, thanks for sharing.

**Comment by mountainmanjed** [comment]
it's not impossible, I need to label stuff. Last year sometime I was working on porting them i got the debug dip switches which is easy. Then worked on the q-sound dev menu never finished it though as i messed up the controls cause i barely labeled anything in the base disassembly.

**Comment by zero800** [comment]
Thanks for answering Jed, I am the creator of the rom hack SF2Mix:
 
(https://www.youtube.com/watch?v=GgkNJ9wTr94&t=4s)  

I made it just using jumps and when I saw your sfa3 code I was fascinated.
It was indispensable Debug's screen to create new things on SF2Mix, so my unusual interest.
I understand perfectly that you have other projects and this requires a lot of your precious time, but just the possibility that one day you can do this makes me very excited.

If you want to exchange messages with me, add me in the discord Zero800#8658
